### ISSUE TITLE
Error when building via `swift build`

### ISSUE THREAD

**Issue by ngryman** [tmandry/AXSwift#10]
Hey,

I'm using the CLI `swift` tool and the integrated package manager. I'm still discovering Swift so I might be missing something obvious.

<details>
<summary><b>Package.swift</b></summary>

```swift
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "sandbox",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/tmandry/AXSwift.git", from: "0.2.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "sandbox",
            dependencies: [
                "AXSwift"
            ]),
    ]
)

```
</details><br>

```
$ swift --version
Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
Target: x86_64-apple-darwin17.4.0
```

Result of `swift build`:

![](https://cdn.zapier.com/storage/photos/7f9b59ef1da6b6b614fa7e46b42e0286.png)

**Comment by tmandry** [comment]
Some of the errors are caused by the wrong version in `Package.swift`. However, it looks like you still can't use SPM to build projects that depend on Cocoa. Unfortunately you'll still have to use Cocoapods or Carthage for that.

Feel free to reopen if I'm wrong about this. In the meantime I'll remove `Package.swift` to reduce confusion.
